export const companyLogoPaths: Partial<Record<string, string>> = {
  ARGIS: "/company-logos/argis.png",
  Adcap: "/company-logos/adcap.png",
  "Agro / Los Grobo": "/company-logos/los-grobo.png",
  "Allaria / BCBA": "/company-logos/allaria-bcba.png",
  "Allaria Ledesma": "/company-logos/allaria-ledesma.png",
  Anker: "/company-logos/anker.png",
  "BYMA / BYMALAB": "/company-logos/byma-bymalab.png",
  Balanz: "/company-logos/balanz.png",
  "Balanz Capital": "/company-logos/balanz-capital.png",
  "Banco Central": "/company-logos/banco-central.png",
  "BroadSpan Capital": "/company-logos/broadspan-capital.png",
  "Brubank / Digital House": "/company-logos/brubank-dh.png",
  "CFA Institute": "/company-logos/cfa-institute.png",
  Citi: "/company-logos/citi.png",
  "Club de Finanzas UTDT": "/company-logos/club-finanzas-utdt.png",
  "Cocos Capital": "/company-logos/cocos-capital.png",
  "Cocos Capital / Glamit": "/company-logos/cocos-glamit.png",
  "Columbus Zuma / UTDT": "/company-logos/columbus-zuma-utdt.png",
  "Consultatio Financial Services": "/company-logos/consultatio.png",
  EY: "/company-logos/ey.png",
  "GST Grupo Financiero": "/company-logos/gst.png",
  Globant: "/company-logos/globant.png",
  "Grupo Financiero Galicia": "/company-logos/galicia.png",
  "Grupo IEB": "/company-logos/grupo-ieb.png",
  "Grupo SBS": "/company-logos/grupo-sbs.png",
  "Grupo Techint": "/company-logos/techint.png",
  HSBC: "/company-logos/hsbc.png",
  "J.P. Morgan": "/company-logos/jp-morgan.png",
  "J.P. Morgan Argentina": "/company-logos/jp-morgan-argentina.png",
  "La Libertad Avanza": "/company-logos/lla.png",
  Lazard: "/company-logos/lazard.png",
  "Liebre Capital": "/company-logos/liebre-capital.png",
  "Maestría en Finanzas UTDT": "/company-logos/mfin-utdt.png",
  "McGill University": "/company-logos/mcgill.png",
  "Ministerio de Economía": "/company-logos/ministerio-economia.png",
  Nubank: "/company-logos/nubank.png",
  "Raízen": "/company-logos/raizen.png",
  "República Argentina": "/company-logos/republica-argentina.png",
  UTDT: "/company-logos/utdt.png",
  "Ualá": "/company-logos/uala.png",
  "Ualá / 17Sigma": "/company-logos/uala-17sigma.png",
  "University Trading Challenge": "/company-logos/utc.png",
  "Vista Energy": "/company-logos/vista-energy.png",
  "Zurich Seguros": "/company-logos/zurich.png"
};
